apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: proxy-ldap-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Ldap Proxy
      kind: LdapProxy
      name: ldapproxies.proxy.ar-consulting.redhat.com
      version: v1alpha1
  description: Proxy to measure communication times between RH-SSO and LDAP
  displayName: ldap-proxy-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Ldap
  - RH-SSO
  links:
  - name: Proxy Ldap Operator
    url: https://proxy-ldap-operator.domain
  maintainers:
  - email: aluque@redhat.com
    name: Abel Luque
  maturity: alpha
  provider:
    name: RedHat ar-consulting
  version: 0.0.0
